const INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR';
const INVALID_REFRESH_TOKEN_ERROR = 'INVALID_REFRESH_TOKEN_ERROR';

module.exports = {
  INVALID_CREDENTIALS_ERROR,
  INVALID_REFRESH_TOKEN_ERROR,
}
