const INVALID_CREDENTIALS_ERROR = 'INVALID_CREDENTIALS_ERROR';
const INVALID_REFRESH_TOKEN_ERROR = 'INVALID_REFRESH_TOKEN_ERROR';
const USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR';

module.exports = {
  INVALID_CREDENTIALS_ERROR,
  INVALID_REFRESH_TOKEN_ERROR,
  USER_NOT_FOUND_ERROR,
}
