const TOKEN_REVOKED = 'TOKEN_REVOKED';
const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
const TOKEN_REQUIRED = 'TOKEN_REQUIRED';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const INVALID_USER_ROLE = 'INVALID_USER_ROLE';
const EMAIL_EXISTS = 'EMAIL_EXISTS';
const USERNAME_EXISTS = 'USERNAME_EXISTS';

module.exports = {
  TOKEN_REVOKED,
  TOKEN_EXPIRED,
  TOKEN_REQUIRED,
  INVALID_CREDENTIALS,
  INVALID_USER_ROLE,
  USERNAME_EXISTS,
  EMAIL_EXISTS
}
