const TOKEN_REVOKED = 'TOKEN_REVOKED';
const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
const TOKEN_REQUIRED = 'TOKEN_REQUIRED';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

module.exports = {
  TOKEN_REVOKED,
  TOKEN_EXPIRED,
  TOKEN_REQUIRED,
  INVALID_CREDENTIALS
}
