const TOKEN_REVOKED = 'TOKEN_REVOKED';
const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
const TOKEN_REQUIRED = 'TOKEN_REQUIRED';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const INVALID_USER_ROLE = 'INVALID_USER_ROLE';
const EXPIRED_OTP = 'EXPIRED_OTP';
const INVALID_OTP = 'INVALID_OTP';

module.exports = {
  TOKEN_REVOKED,
  TOKEN_EXPIRED,
  TOKEN_REQUIRED,
  INVALID_CREDENTIALS,
  INVALID_USER_ROLE,
  EXPIRED_OTP,
  INVALID_OTP,
}
